name: Prepare Next Development Iteration

on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: Version number of the next iteration
        required: true

jobs:
  Next-Iteration-Job:
    name: Next Iteration Job
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Sources
        uses: actions/checkout@v4
        
      - name: Update Version Number
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config user.email "tomasz.tylenda@sonarsource.com"
          git config user.name "Tomasz Tylenda"
          git checkout -b gh-action/next-iteration
          mvn versions:set -DgenerateBackupPoms=false -DnewVersion="${{ inputs.nextVersion }}"
          git commit -m 'Prepare next development iteration' -a
          git push --set-upstream origin gh-action/next-iteration
          gh pr create -B main --title 'Prepare next development iteration' --body ''
