name: Prepare Next Development Iteration

on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: Version number of the next iteration
        required: true

jobs:
  Next-Iteration-Job:
    name: Next Iteration Job
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Sources
        uses: actions/checkout@v4
        
      - name: Update Version Number
        run: |
          git config --global user.email "tomasz.tylenda@sonarsource.com"
          git config --global user.name "Tomasz Tylenda"
          git checkout -b bump-iteration
          mvn versions:set -DgenerateBackupPoms=false -DnewVersion=1.1-SNAPSHOT
          git commit -m 'Prepare next development iteration' -a
          git push --set-upstream origin version
          gh pr create -B main --title 'Prepare next development iteration' --body ''
